import type { Component } from 'svelte';

/**
 * Lazy component map — each tool page only downloads its own component
 * (plus whatever libraries that tool needs, e.g. yaml or bcrypt).
 */
export const TOOL_COMPONENTS: Record<string, () => Promise<{ default: Component }>> = {
	'json-formatter': () => import('./JsonFormatterTool.svelte'),
	'base64-decode': () => import('./Base64Tool.svelte'),
	'timestamp-converter': () => import('./TimestampTool.svelte'),
	'jwt-decoder': () => import('./JwtTool.svelte'),
	'regex-tester': () => import('./RegexTool.svelte'),
	'diff-checker': () => import('./DiffTool.svelte'),
	'url-encode-decode': () => import('./UrlTool.svelte'),
	'url-parser': () => import('./UrlParserTool.svelte'),
	'uuid-generator': () => import('./UuidTool.svelte'),
	'hash-generator': () => import('./HashTool.svelte'),
	'color-converter': () => import('./ColorTool.svelte'),
	'case-converter': () => import('./CaseConverterTool.svelte'),
	'word-counter': () => import('./WordCounterTool.svelte'),
	'lorem-ipsum-generator': () => import('./LoremTool.svelte'),
	'slug-generator': () => import('./SlugTool.svelte'),
	'sort-lines': () => import('./SortLinesTool.svelte'),
	'html-entities': () => import('./HtmlEntitiesTool.svelte'),
	'unicode-inspector': () => import('./UnicodeTool.svelte'),
	'cron-parser': () => import('./CronTool.svelte'),
	'password-generator': () => import('./PasswordTool.svelte'),
	'qr-code-generator': () => import('./QrTool.svelte'),
	'qr-code-decoder': () => import('./QrDecodeTool.svelte'),
	'json-to-yaml': () => import('./JsonYamlTool.svelte'),
	'json-to-csv': () => import('./JsonCsvTool.svelte'),
	'json-to-typescript': () => import('./JsonTsTool.svelte'),
	'jsonpath-tester': () => import('./JsonPathTool.svelte'),
	'bcrypt-generator': () => import('./BcryptTool.svelte'),
	'user-agent-parser': () => import('./UaTool.svelte'),
	'image-to-base64': () => import('./ImageBase64Tool.svelte'),
	'image-converter': () => import('./ImageConvertTool.svelte'),
	'image-resizer': () => import('./ImageResizeTool.svelte'),
	'favicon-generator': () => import('./FaviconTool.svelte'),
	'sql-formatter': () => import('./SqlFormatterTool.svelte'),
	'xml-formatter': () => import('./XmlFormatterTool.svelte'),
	'xml-to-json': () => import('./XmlJsonTool.svelte'),
	'markdown-to-html': () => import('./MarkdownTool.svelte'),
	'html-formatter': () => import('./HtmlFormatterTool.svelte'),
	'css-formatter': () => import('./CssFormatterTool.svelte'),
	'js-formatter': () => import('./JsFormatterTool.svelte'),
	'string-escape': () => import('./StringEscapeTool.svelte'),
	'number-base-converter': () => import('./NumberBaseTool.svelte'),
	'text-to-hex': () => import('./HexBinTool.svelte'),
	'json-schema-validator': () => import('./JsonSchemaTool.svelte'),
	'exif-viewer': () => import('./ExifTool.svelte')
};
