/**
 * Post-build step: wrap the adapter-generated Worker with a canonical-host
 * redirect (www → apex, 301).
 *
 * Why here: the site is fully prerendered, and adapter-cloudflare owns the
 * `main` entry (it overwrites whatever path wrangler's `main` points at on
 * every build), while Workers `_redirects` files don't support domain-level
 * rules. So after `vite build` we rename the generated worker and drop a
 * thin wrapper in its place. Combined with `run_worker_first` in
 * wrangler.jsonc, every page request hits the redirect check first.
 *
 * Runs as part of `pnpm build` — see package.json.
 */

import { readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = join(dirname(fileURLToPath(import.meta.url)), '..', '.svelte-kit', 'cloudflare');
const entry = join(dir, '_worker.js');
const inner = join(dir, 'kit-worker.js');

const MARKER = 'CANONICAL_HOST_WRAPPER';

if (readFileSync(entry, 'utf8').includes(MARKER)) {
	console.log('wrap-worker: entry already wrapped, skipping');
	process.exit(0);
}

renameSync(entry, inner);
writeFileSync(
	entry,
	`// ${MARKER} — generated by scripts/wrap-worker.mjs, do not edit.
import kit from './kit-worker.js';

export default {
	async fetch(request, env, ctx) {
		const url = new URL(request.url);
		if (url.hostname === 'www.onlinetools.dev') {
			url.hostname = 'onlinetools.dev';
			return Response.redirect(url.toString(), 301);
		}
		return kit.fetch(request, env, ctx);
	}
};
`
);
console.log('wrap-worker: canonical-host wrapper installed');
